export interface Wilaya {
  code: string;
  nameAr: string;
  nameFr: string;
}

export const WILAYAS: Wilaya[] = [
  { code: "01", nameAr: "01 - أدرار", nameFr: "01 - Adrar" },
  { code: "02", nameAr: "02 - الشلف", nameFr: "02 - Chlef" },
  { code: "03", nameAr: "03 - الأغواط", nameFr: "03 - Laghouat" },
  { code: "04", nameAr: "04 - أم البواقي", nameFr: "04 - Oum El Bouaghi" },
  { code: "05", nameAr: "05 - باتنة", nameFr: "05 - Batna" },
  { code: "06", nameAr: "06 - بجاية", nameFr: "06 - Béjaïa" },
  { code: "07", nameAr: "07 - بسكرة", nameFr: "07 - Biskra" },
  { code: "08", nameAr: "08 - بشار", nameFr: "08 - Béchar" },
  { code: "09", nameAr: "09 - البليدة", nameFr: "09 - Blida" },
  { code: "10", nameAr: "10 - البويرة", nameFr: "10 - Bouira" },
  { code: "11", nameAr: "11 - تمنراست", nameFr: "11 - Tamanrasset" },
  { code: "12", nameAr: "12 - تبسة", nameFr: "12 - Tébessa" },
  { code: "13", nameAr: "13 - تلمسان", nameFr: "13 - Tlemcen" },
  { code: "14", nameAr: "14 - تيارت", nameFr: "14 - Tiaret" },
  { code: "15", nameAr: "15 - تيزي وزو", nameFr: "15 - Tizi Ouzou" },
  { code: "16", nameAr: "16 - الجزائر", nameFr: "16 - Alger" },
  { code: "17", nameAr: "17 - الجلفة", nameFr: "17 - Djelfa" },
  { code: "18", nameAr: "18 - جيجل", nameFr: "18 - Jijel" },
  { code: "19", nameAr: "19 - سطيف", nameFr: "19 - Sétif" },
  { code: "20", nameAr: "20 - سعيدة", nameFr: "20 - Saïda" },
  { code: "21", nameAr: "21 - سكيكدة", nameFr: "21 - Skikda" },
  { code: "22", nameAr: "22 - سيدي بلعباس", nameFr: "22 - Sidi Bel Abbès" },
  { code: "23", nameAr: "23 - عنابة", nameFr: "23 - Annaba" },
  { code: "24", nameAr: "24 - قالمة", nameFr: "24 - Guelma" },
  { code: "25", nameAr: "25 - قسنطينة", nameFr: "25 - Constantine" },
  { code: "26", nameAr: "26 - المدية", nameFr: "26 - Médéa" },
  { code: "27", nameAr: "27 - مستغانم", nameFr: "27 - Mostaganem" },
  { code: "28", nameAr: "28 - المسيلة", nameFr: "28 - M'Sila" },
  { code: "29", nameAr: "29 - معسكر", nameFr: "29 - Mascara" },
  { code: "30", nameAr: "30 - ورقلة", nameFr: "30 - Ouargla" },
  { code: "31", nameAr: "31 - وهران", nameFr: "31 - Oran" },
  { code: "32", nameAr: "32 - البيض", nameFr: "32 - El Bayadh" },
  { code: "33", nameAr: "33 - إليزي", nameFr: "33 - Illizi" },
  { code: "34", nameAr: "34 - برج بوعريريج", nameFr: "34 - Bordj Bou Arréridj" },
  { code: "35", nameAr: "35 - بومرداس", nameFr: "35 - Boumerdès" },
  { code: "36", nameAr: "36 - الطارف", nameFr: "36 - El Tarf" },
  { code: "37", nameAr: "37 - تندوف", nameFr: "37 - Tindouf" },
  { code: "38", nameAr: "38 - تسمسيلت", nameFr: "38 - Tissemsilt" },
  { code: "39", nameAr: "39 - الوادي", nameFr: "39 - El Oued" },
  { code: "40", nameAr: "40 - خنشلة", nameFr: "40 - Khenchela" },
  { code: "41", nameAr: "41 - سوق أهراس", nameFr: "41 - Souk Ahras" },
  { code: "42", nameAr: "42 - تيبازة", nameFr: "42 - Tipaza" },
  { code: "43", nameAr: "43 - ميلة", nameFr: "43 - Mila" },
  { code: "44", nameAr: "44 - عين الدفلى", nameFr: "44 - Aïn Defla" },
  { code: "45", nameAr: "45 - النعامة", nameFr: "45 - Naâma" },
  { code: "46", nameAr: "46 - عين تموشنت", nameFr: "46 - Aïn Témouchent" },
  { code: "47", nameAr: "47 - غرداية", nameFr: "47 - Ghardaïa" },
  { code: "48", nameAr: "48 - غليزان", nameFr: "48 - Relizane" },
  { code: "49", nameAr: "49 - تيميمون", nameFr: "49 - Timimoun" },
  { code: "50", nameAr: "50 - برج باجي مختار", nameFr: "50 - Bordj Badji Mokhtar" },
  { code: "51", nameAr: "51 - أولاد جلال", nameFr: "51 - Ouled Djellal" },
  { code: "52", nameAr: "52 - بني عباس", nameFr: "52 - Béni Abbès" },
  { code: "53", nameAr: "53 - عين صالح", nameFr: "53 - In Salah" },
  { code: "54", nameAr: "54 - عين قزام", nameFr: "54 - In Guezzam" },
  { code: "55", nameAr: "55 - تقرت", nameFr: "55 - Touggourt" },
  { code: "56", nameAr: "56 - جانت", nameFr: "56 - Djanet" },
  { code: "57", nameAr: "57 - المغير", nameFr: "57 - El M'Ghair" },
  { code: "58", nameAr: "58 - المنيعة", nameFr: "58 - El Meniaa" },
];
