// This file is the entry point for Hostinger / cPanel Node.js environments
// It simply requires the built standalone server generated by Next.js
try {
  require('./.next/standalone/server.js');
} catch (err) {
  console.error("Failed to start the standalone server. Make sure you have run 'npm run build' first.", err);
  process.exit(1);
}
